spring:
  application:
    name: capability-service

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: store_app
    password: StoreApp123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2s
      timeout: 2s
      repositories:
        enabled: false

  cache:
    type: redis

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,caches

logging:
  level:
    org.springframework.cache.interceptor.CacheInterceptor: TRACE

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

store-service:
  base-url: http://localhost:8081
  connect-timeout-ms: 2000
  read-timeout-ms: 3000

app:
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000
